### ISSUE TITLE
'Config' object has no attribute 'users'

### ISSUE THREAD

**Issue by ledetav** [Karlend/telespy#2]
At the first start, this occurs:
```
[2022-12-14 18:07:40,586] asyncio (ERROR) -> Task exception was never retrieved
future: <Task finished name='Task-21' coro=<load_users() done, defined at C:\Users\nordh\Desktop\online-spy\telespy\telespy\main.py:12> exception=AttributeError("'Config' object has no attribute 'users'")>
Traceback (most recent call last):
  File "C:\Users\nordh\Desktop\online-spy\telespy\telespy\main.py", line 13, in load_users
    users = config.get_users()
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nordh\Desktop\online-spy\telespy\telespy\config.py", line 118, in get_users
    return self.users
           ^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'users'
```

**Comment by Karlend** [comment]
Fixed
https://github.com/Karlend/telespy/commit/0b809552f7b948831ba1774bb5fd2071704184f9
